# Generated by Django 3.0 on 2020-04-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handouts',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='videos',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='HandoutsCategory',
        ),
        migrations.DeleteModel(
            name='VideoCategory',
        ),
    ]
